# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'package'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students Starter(0ee7c0e4-8e6c-4ce5-9b0c-3c22f09015b1)'
    appType: 'webApp'
    WebAppName: 'java-web-app-cloud-demo'
    deployToSlotOrASE: true
    ResourceGroupName: 'Cloud_Demo'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.war'